config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  get    'login'   => 'login#index'
  post   'login'   => 'login#create'
  delete 'logout'   => 'login#destroy'
  get    'signup'  => 'signup#index'
  post   'signup'  => 'signup#create'
  get    'items' => 'items#index'

  scope '/api' do
    scope '/v1' do
      scope '/items' do
        get '/' => 'api/items#list'
        post '/' => 'api/items#create'
        scope '/:name' do
          get '/' => 'api/items#show'
          put '/' => 'api/items#update'
          delete '/' => 'api/items#delete'
        end
      end
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
	before_save { self.username = username.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/api/items_controller.rb
#encoding: UTF-8
module Api	
	class ItemsController < ApiBaseController


	  def list
  		@items = current_user.items
  		render json: @items
	  end

	  def create
  		new_item = Item.new(params).save
  		new_item.user = current_user
  		if new_item.save
  			render json: new_item
  		else
  			render json: {error: 'Could not store item'}, status: 409
  		end
	  end

	  def show
	  	@item = Item.find_by_id(params[:name])
	  	unless @item.nil?
	  		render json: @item
	  	else
	  		render json: {error: 'Not Found'}, status: 404
	  	end
	  end	  

	  def update
	  	@item = Item.find_by_id(params[:name])
	  	unless @item.nil?
	  		if @items.update(params)
	  			render json: @item
	  		else
	  			render json: {error: 'Could not be updated'}, status: 409
	  		end
	  	else
	  		render json: {error: 'Not Found'}, status: 404
	  	end
	  end	  

	  def delete
	  	unless Item.delete(params[:name])
	  		render status: 200
	  	else
	  		render json: {error: 'Not Found'}, status: 404
	  	end
	  end	  

	end
end

app/controllers/api_base_controller.rb
#encoding: UTF-8
class ApiBaseController < ApplicationController

	skip_before_filter :secure_app

	before_filter :api_secure

	def api_secure
		authenticate_or_request_with_http_token do |token, options|
			token == Rails.application.config.api_resource_secret
		end
		render json: {error: 'User could not be detected'}, status: 401 if current_user.nil?
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_filter :secure_app

  def current_user
  	@current_user ||= User.find_by(username: session[:user_id]) if session.has_key?(:user_id)
  	@current_user
  end

  def add_user(user)
    session[:user_id] = user.username
  end

  def user_service
    UserService.new(params)
  end

  private
  def secure_app
  	redirect_to controller: 'login' if current_user.nil?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = current_user.items
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

	skip_before_filter :secure_app
	def index
	end

	def destroy
		session.destroy
		redirect_to root_path
	end

	def create
		user, result = user_service.login
		unless user.nil?
			add_user user
			redirect_to items_path
		else
			flash.now[:danger] = t(result)
 			render :index
		end
	end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
	skip_before_filter :secure_app
	layout "login"
	
	def index
	end

	def create
		created = user_service.register
		if created 
			redirect_to items_path
		else
			flash.now[:danger] = t(:could_not_create_user)
			render :index
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/items/index.html.erb
<h1>Items Lists</h1>
 
<table class="table">
  <tr>
    <th>Link</th>
    <th>Link Type</th>
    <th>Description</th>
  </tr>
 
  <% @items.each do |item| %>
    <tr>
      <td><%= item.link %></td>
      <td><%= item.link_type %></td>
      <td><%= item.description %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MyApp</a>        
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="fa fa-user" aria-hidden="true"></span> <%= current_user.username%></a>
              <ul class="dropdown-menu" role="menu">
                <li class="divider"></li>
                <li><li><%= link_to "Log out", logout_path, method: :delete %></li></li>
              </ul>
            </li>
          </ul>        
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MyApp</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/login/index.html.erb
<% provide(:title, "Log in") %>

<div class="row">
  <div class="col-md-6 col-md-offset-5">
    <%= form_for(:login, url: login_url, html: {"class" => "form-signin"}) do |f| %>
      
      <h2 class="form-singin-header">Log in</h1>

      <%= f.label :email, class: 'sr-only' %>
      <%= f.email_field :email, class: 'form-control', placeholder: 'Email Address' %>

      <%= f.label :password, class: 'sr-only' %>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_url %></p>
  </div>
</div>

app/views/signup/index.html.erb
<% provide(:title, "SignUp") %>

<div class="row">
  <div class="col-md-6 col-md-offset-5">
    <%= form_for(:signup, url: signup_url, html: {"class" => "form-signin"}) do |f| %>
      
      <h2 class="form-singin-header">Singup new User</h1>

      <%= f.label :username, class: 'sr-only' %>
      <%= f.email_field :username, class: 'form-control', placeholder: 'Email Address' %>

      <%= f.label :password, class: 'sr-only' %>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

      <%= f.submit "Singup", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>